dashboard/urls.py
from django.urls import path
from .views import *
app_name='dashboard'

urlpatterns = [
    path('', Dashboard.as_view(), name='dashboard'),
    path('signup/', user_signup, name='signup'),
    path('logout/', user_logout, name='logout'),
    path('login/', user_login, name='user_login'),
    path('profile/', ProfileView.as_view(), name='profile_view'),
    path('courses/', ShortTermCourses.as_view(), name='short_term_courses'),
    path('courses/add/', CourseCreate.as_view(), name='course_create'),
    path('courses/<str:course_id>/edit/', CourseEdit.as_view(), name='course_edit'),
    path('courses/<str:course_id>/delete/', CourseDelete.as_view(), name='course_delete'),
    
]

eduportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    title = models.CharField(max_length=250, blank=True)
    subtitle = models.CharField(max_length=250, blank=True)
    amount = models.PositiveIntegerField(null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    image = models.FileField(upload_to='course_images', blank=True, null=True)
    is_active = models.BooleanField("Active",default=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    
    def __str__(self):
        return self.title

dashboard/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from dashboard.models import Course

class SignupForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ['username', 'password1', 'password2']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
    

class CourseForm(forms.ModelForm):
    name = forms.CharField( 
        label="Title", max_length=100,min_length=2, required = True,
        widget=forms.TextInput(attrs={'autocomplete':'off', 'class': 'pop-input-feild'}),
        error_messages={ 'required': 'The name should not be empty',
                        'min_length': 'The name should not be less than 2 characters',
                        'max_length': 'The name should not exceed 100 characters',
                        }
    )
    
    description = forms.CharField(
        widget=forms.Textarea(attrs={"class": "login-input-feild", "maxlength": 100})
    )
  
    from_age = forms.IntegerField(
         label="From age", required=True,
         widget=forms.TextInput(),
         error_messages={'required': 'The from age should not be empty',
                         'invalid': 'invalid age'}
    )
    to_age = forms.IntegerField(
         label="To age", required=True,
         widget=forms.TextInput(),
         error_messages={'required': 'The to age should not be empty',
                         'invalid': 'invalid age'}
    )
    class Meta:
        model = Course
        fields = ['name', 'description','from_age','to_age']
    
    def clean(self):
        cleaned_data = super(CourseForm, self).clean()
        from_age = cleaned_data.get("from_age")
        to_age = cleaned_data.get("to_age")
        if from_age and to_age and to_age < from_age:
            self.add_error('to_age', 'To age should be greater than from age.')
        return cleaned_data 

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout 
from .forms import UserCreationForm, LoginForm
from django.shortcuts import render
from django.views import View
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from .models import Course
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.core.paginator import *
from django.shortcuts import get_object_or_404
from django.db import transaction
from .helper import is_ajax
from django.contrib.auth.models import User
from django.contrib import messages



# Create your views here.
def index(request):
    return render(request, 'index.html')


def user_signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)    
                return HttpResponseRedirect('/')
    else:
        form = LoginForm()
    return render(request, 'dashboard/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('login')


class Dashboard(LoginRequiredMixin,View):
    template_name = "dashboard/index.html"
    def get(self, request, *args, **kwargs):
        datas = {}
        return render(request, self.template_name, datas)
    

class ProfileView(LoginRequiredMixin,View):
    template_name = "dashboard/profile/index.html"
    def get(self, request, *args, **kwargs):
        datas = {}
        datas['user_id']= request.user.id
        return render(request, self.template_name, datas)
    
    def post(self, request, *args, **kwargs):
        userid = request.POST.get('user_id')
        current_passowrd =  request.POST.get('current_passowrd')
        pwd = request.POST.get('new_password')
        cpwd = request.POST.get('confirm_password')

        try:
            user = User.objects.get(pk=userid)
        except User.DoesNotExist:
            user = None
        if pwd == cpwd:
        
            if user:
                user.set_password(pwd)
                user.save()
                messages.success(request, 'password change success')
                return HttpResponseRedirect('/')
            else:
                messages.error(request, 'Please Try again')
                return render(request, 'dashboard/profile/index.html')

        else:
            messages.error(request, "password doesnot match")
            return render(request, 'dashboard/profile/index.html')

    

class ShortTermCourses(LoginRequiredMixin, View):
    template_name = "dashboard/courses/index.html"
    
    def get(self, request, *args, **kwargs):
        filter_conditions = {}
        
        if is_ajax(request=request):
            query = request.GET.get('query', None)
            filter_conditions['title__icontains'] = query
            
        courses = Course.objects.filter(**filter_conditions)
        try:
            page = int(request.GET.get("page", 1))
        except ValueError:
            page = 1

        paginator = Paginator(courses, 2)

        try:
            courses = paginator.page(page)
        except PageNotAnInteger:
            courses = paginator.page(1)  
        except EmptyPage:
            courses = paginator.page(paginator.num_pages)
            
        if is_ajax(request=request):
            context = {}
            context['courses']= courses
            response = {"status": True,
                        "pagination": render_to_string("dashboard/courses/courses_pagination.html", context=context, request=request),
                        "template": render_to_string("dashboard/courses/courses_list.html", context, request=request),}
            return JsonResponse(response)
            
        datas = {'courses':courses, 'current_page': page}
        return render(request, self.template_name, datas)
    

class CourseCreate(LoginRequiredMixin, View):
    template_name = "dashboard/courses/course_form.html"

    def get(self, request, *args, **kwargs):
        data = {}
        context = {}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        response = {}
       
        try:
            with transaction.atomic():
                create_conditions, data = {}, {}
                title = request.POST.get('title', None)
                subtitle = request.POST.get('subtitle', None)
                description = request.POST.get('description', None)
                amount = request.POST.get('amount', None)
                status = request.POST.get('status', None)
                course_image = request.FILES.get('course_image', None)
                
                # CHECK THE DATA EXISTS
                if Course.objects.filter(title=title).exists():
                    data['status'] = False
                    data['message'] = 'Data already exists'
                else:
                    if title:
                        create_conditions['title']= title
                    if subtitle:
                        create_conditions['subtitle']= subtitle
                    if description:
                        create_conditions['description']= description
                    if amount:
                        create_conditions['amount']= amount
                    if status:
                        create_conditions['is_active']= True
                    if course_image:
                        create_conditions['image']= course_image
                    Course.objects.create(**create_conditions)
                    data['status'] = True
                    data['message'] = 'course created successfully'
                    data['redirect_url'] = '/courses/'
        except Exception as error:
            response["status"] = False
            response["message"] = "Something went wrong"
       
        return JsonResponse(data)
    
    

class CourseEdit(LoginRequiredMixin, View):
    template_name = "dashboard/courses/course_form.html"

    def get(self, request, course_id, *args, **kwargs):
        course = get_object_or_404(Course, id=course_id)
        context = {'course': course, 'id':course_id}
        return render(request, self.template_name, context)

    def post(self, request, course_id, *args, **kwargs):
        response = {}
        try:
            with transaction.atomic():
                update_conditions, data = {}, {}
                
                # Retrieve data from the POST request
                title = request.POST.get('title', None)
                subtitle = request.POST.get('subtitle', None)
                description = request.POST.get('description', None)
                amount = request.POST.get('amount', None)
                status = request.POST.get('status', None)
                course_image = request.FILES.get('course_image', None)
                
                # CHECK THE DATA EXISTS
                if Course.objects.exclude(id=course_id).filter(title=title).exists():
                    data['status'] = False
                    data['message'] = 'Data already exists'
                else:
                    if title:
                        update_conditions['title'] = title
                    if subtitle:
                        update_conditions['subtitle'] = subtitle
                    if description:
                        update_conditions['description'] = description
                    if amount:
                        update_conditions['amount'] = amount
                    if status:
                        update_conditions['is_active'] = True
                    if course_image:
                        update_conditions['image'] = course_image
                    
                    # Update the existing course instance
                    Course.objects.filter(id=course_id).update(**update_conditions)
                    print('pppojoj')
                    
                    data['status'] = True
                    data['message'] = 'Course updated successfully'
                    data['redirect_url'] = '/courses/'
        except Exception as error:
            response["status"] = False
            response["message"] = "Something went"
        return JsonResponse(data)
    
    
    
class CourseDelete(LoginRequiredMixin, View):
    template_name = "dashboard/courses/course_form.html"

    def get(self, request, course_id, *args, **kwargs):
        response = {}
        try:
            with transaction.atomic():
                course = get_object_or_404(Course, id=course_id)
                course.delete()
                return HttpResponseRedirect('/courses/')
        except Exception as error:
            response["status"] = False
            response["message"] = f"Error: {error}"

        return JsonResponse(response)

templates/dashboard/courses/course_form.html
{% extends "dashboard/layout/base.html" %} {% load static %} {% block body_block %}
{% include 'dashboard/layout/header.html' %}





<!--app-content open-->
<div class="main-content app-content mt-0">
  <div class="side-app">
    <!-- CONTAINER -->
    <div class="main-container container-fluid">
      <!-- PAGE-HEADER -->
      <div class="page-header">
        <h1 class="page-title">Short Term Course Create</h1>
        <a href="{% url 'dashboard:short_term_courses' %}" class="btn btn-danger btn-pill">View</a>
      </div>
      <!-- PAGE-HEADER END -->
      <form {% if id  %}  action="{% url 'dashboard:course_edit' id %}"{% else %} action="{% url 'dashboard:course_create' %}" {% endif %} method="post" class="CourseForm" name="CourseForm" id="CourseForm" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
          <!-- IMAGE UPLOADER -->
          <div class="col-lg-4 col-md-6">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Image Upload</h3>
              </div>
              <div class=" card-body">
                <div class="row mb-5">
                  <div class="col-lg-12 col-sm-12 mb-4 mb-lg-0">
                    <input type="file" class="dropify" data-bs-height="180" name='course_image' id='course_image' />
                  </div>
                </div>
              </div>
            </div>
          </div>
          <!-- IMAGE UPLOADER end -->
          <!-- DETAILS START -->
          <div class="col-lg-8">
            <div class="card">
              <div class="card-header">
                <h3 class="card-title">Short Term Course Information</h3>
              </div>
              <div class="card-body">
                <div class="row">
                  <!--  Title -->
                  <div class="col-sm-6 col-md-6">
                    <div class="form-group">
                      <label class="form-label"> Title</label>
                      <input type="text" class="form-control" placeholder=" Title" name="title" {% if course %}value="{{course.title}}"{% endif %}>
                    </div>
                  </div>
                  <!--  Subtitle -->
                  <div class="col-sm-6 col-md-6">
                    <div class="form-group">
                      <label class="form-label">Subtitle</label>
                      <input type="text" class="form-control" placeholder="Subtitle" name='subtitle'  {% if course %}value="{{course.subtitle}}"{% endif %}>
                    </div>
                  </div>
                  <!-- Description -->
                  <div class="col-md-12">
                    <div class="form-group">
                      <label class="form-label">Description</label>
                      <div id="summernote"></div>
                    </div>
                  </div>

                  <div class="form-group">
                    <div class="multi-field-wrapper ">
                      <div class="multi-fields">
                        <div class="multi-field">
                          <div class="row">
                            <div class="col-lg-6" style="padding-right:0px">
                              <div class="form-group">
                                <label>Amount</label>
                                <input type="number" min='0' name="amount" class="form-control form-control-lg" placeholder="Value"  {% if course %}value="{{course.amount}}"{% endif %}>
                              </div>
                            </div>
                            <div class="col-lg-6" style="padding-right:0px">
                              <div class="form-group">
                                <label>Description</label>
                                <textarea class="form-control mb-4" placeholder="Textarea" name='description'>
                                  {% if course %}{{course.description}} {% endif %}
                                </textarea>
                              </div>
                            </div>
                          </div>
                          <button type="button" class="remove-field float-right btn btn-danger btn-sm icon-btn ml-2 ">
                            <i class="mdi mdi-delete"></i>
                          </button>
                        </div>
                      </div>
                      <div>
                        <button type="button" type="button" class=" add-field btn btn-info btn-sm icon-btn ml-2 mb-2"> Add New <i class="mdi mdi-plus"></i>
                        </button>
                      </div>
                    </div>
                  </div>

                  <!-- status -->
                  <div class="col-md-6">
                    <div class="form-group">
                      <label class="form-label">Status</label>
                      <select class="form-control select2" data-placeholder="Status" name='status'>
                        <option value="Enable"  {% if course %}{% if course.is_active %}selected{% endif %}{% endif %}>Enable</option>
                        <option value="Disable" {% if course %}{% if not course.is_active %}selected{% endif %}{% endif %}>Disable</option>
                      </select>
                    </div>
                  </div>
                  <!-- SUBMIT START -->
                  <div class="col-lg-12 ">
                    <div class="mt-5">
                      <button  class="btn btn-default btn-pill">Cancel</button>
                      <button  class="btn btn-warning btn-pill submit_btn" id="submit_btn">Submit</button>
                    </div>
                  </div>
                  <!-- SUBMIT END -->
                </div>
              </div>
            </div>
          </div>
          <!-- DETAILS END -->
        </div>
    </div>
    </form>
  </div>
  <!-- CONTAINER END -->
</div>
</div>
<!--app-content close--> 
{% endblock %} 

<script>
  $('.multi-field-wrapper').each(function() {
    var $wrapper = $('.multi-fields', this);
    $(".add-field", $(this)).click(function(e) {
      $('.multi-field:first-child', $wrapper).clone(true).appendTo($wrapper).find('input,textarea').val('').focus();
    });
    $('.multi-field .remove-field', $wrapper).click(function() {
      if ($('.multi-field', $wrapper).length > 1) $(this).parent('.multi-field').remove();
    });
  });
</script>

templates/dashboard/courses/courses_list.html
<table class="table border text-nowrap text-md-nowrap table-hover mb-0">
    <thead>
      <tr>
        <th>Sl No</th>
        <th>Image</th>
        <th>Title</th>
        <th>Subtitle</th>
        <th>Description</th>
        <th>Details</th>
        <th>Satus</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <!-- TABLE DETAILS -->
      {% for course in courses %}
      <tr>
        <td>{{forloop.counter}}</td>
        <td>
          <img class="d-block img-fluid br-5 img-td" src="{% if course.image %}{{course.image.url}}{% endif %}" alt="">
        </td>
        <td> {{course.title}}</td>
        <td> {{course.subtitle}} </td>
        <td>
          <a class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#description">
            <i class="side-menu__icon fe fe-eye text-white"></i>
          </a>

          <div class="modal  fade" id="description" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-md modal-dialog-centered text-center" role="document">
              <div class="modal-content ">
                <div class="modal-body">
                  <button aria-label="Close" class="btn-close position-absolute" data-bs-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  <h4 class="text-primary">Description</h4>
                  <p class="mg-b-20 mg-x-20">{{course.description}}</p>
                </div>
              </div>
            </div>
          </div>
        </td>
        <td>
          <a class="btn btn-dark" data-bs-toggle="modal" data-bs-target="#crsdetail">
            <i class="side-menu__icon fe fe-list text-white"></i>
          </a>

          <div class="modal  fade" id="crsdetail" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-lg modal-dialog-centered text-center" role="document">
              <div class="modal-content ">
                <div class="modal-body">
                  <button aria-label="Close" class="btn-close position-absolute" data-bs-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  <table class="table table-striped">
                    <thead>
                      <tr>
                        <th>Title</th>
                        <th>Description</th>
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <td>Title</td>
                        <td>{{course.title}}</td>
                      </tr>
                      <tr>
                        <td>Subtitle</td>
                        <td>{{course.subtitle}}</td>
                      </tr>
                      <tr>
                        <td>Description</td>
                        <td>{{course.description}}</td>
                      </tr>
                    </tbody>
                  </table>
                </div>
                <div class="modal-footer justify-content-center">
                  <button aria-label="Close" class="btn btn-danger pd-x-25" data-bs-dismiss="modal">Cancel</button>
                </div>
              </div>
            </div>

        </td>
        <td>
          {% if course.is_active %}
          <a href="">
            <span class="btn btn-success">Active</span>
          </a>
          {% else %}
          <a href="">
            <span class="btn btn-danger">Inactive</span>
          </a>

          {% endif %}
          
          
        </td>
        <td>
          <a class=" btn btn-info" href="{% url 'dashboard:course_edit' course.id %}">
            <i class="side-menu__icon fe fe-edit"></i>
          </a>
          <a class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#modaldemo{{course.id}}">
            <i class="side-menu__icon fe fe-trash text-white"></i>
          </a>

          <div class="modal  fade" id="modaldemo{{course.id}}" tabindex="-1" role="dialog">
            <div class="modal-dialog modal-md modal-dialog-centered text-center" role="document">
              <div class="modal-content ">
                <div class="modal-body">
                  <button aria-label="Close" class="btn-close position-absolute" data-bs-dismiss="modal">
                    <span aria-hidden="true">&times;</span>
                  </button>
                  <i class="icon icon-close fs-70 text-danger lh-1 my-5 d-inline-block"></i>
                  <h4 class="text-danger">Are You Sure Do You Want To Delete ?</h4>
                  <p class="mg-b-20 mg-x-20">Item Will be Deleted Permanently</p>
                </div>
                <div class="modal-footer justify-content-center">
                  <a href="{% url 'dashboard:course_delete' course.id %}" class="btn btn-success">Yes</a>
                  <button aria-label="Close" class="btn btn-danger pd-x-25" data-bs-dismiss="modal">Cancel</button>
                </div>
              </div>
            </div>
          </div>

        </td>
      </tr>
      {% endfor %}
      
      <!-- TABLE DETAILS END -->
    </tbody>
  </table>

templates/dashboard/courses/courses_pagination.html
<input type="hidden" id="page" value="1" />
<input type="hidden" id="current_page" value="{{current_page}}" />
<input type="hidden" id="start_count" value="1" />

{% if courses.has_other_pages %}
  <ul class="pagination">
    {% if courses.has_previous %}
      <li class="page-item page-prev"><a class="page-link" href="?page={{ courses.previous_page_number }}">Prev</a></li>
    {% else %}
      <li class="page-item page-prev" class="disabled"><span></span></li>
    {% endif %}

    {% for i in courses.paginator.page_range %}
      {% if courses.number == i %}
        <li class="page-item active" >
          {% comment %} <span>{{ i }} <span class="sr-only">(current)</span></span> {% endcomment %}
          <a class="page-link" href="">{{i}}</a>
        </li>
      {% else %}
        <li class="page-item "><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if courses.has_next %}
      <li class="page-item page-next"><a class="page-link"  href="?page={{ courses.next_page_number }}">Next</a></li>
    {% else %}
      <li class="disabled page-item page-next"><span></span></li>
    {% endif %}
  </ul>
{% endif %}

templates/dashboard/courses/index.html
{% extends "dashboard/layout/base.html" %} {% load static %} {% block body_block %} 
{% include 'dashboard/layout/header.html' %}
<!--app-content open-->
<div class="main-content app-content mt-0">
  <div class="side-app">
    <!-- CONTAINER -->
    <div class="main-container container-fluid">
      <!-- PAGE-HEADER -->
      <div class="page-header">
        <h1 class="page-title">Short Term Course View</h1>
        <a href="{% url 'dashboard:course_create' %}" class="btn btn-danger btn-pill">Add <i class="fa fa-plus"></i>
        </a>
      </div>
      <!-- PAGE-HEADER END -->
      <div class="row">
        <div class="col-xl-12">
          <div class="card">
            <div class="card-header">
              <h3 class="card-title">Short Term Course Table</h3>
            </div>
            <div class="card-body">

              <div class="table-responsive">
                <input name='filter_courses' style='padding-bottom:10px;' id="filter_courses" class="filter_courses form-control" placeholder='Type here to filter courses' onkeyup="FilterCourse('')">
                <div class="table-responsive" id="course_table">
                    {% include 'dashboard/courses/courses_list.html' %}
                  
                </div>
                <div class="card-body" id="course_pagination">
                    {% include 'dashboard/courses/courses_pagination.html' %}
                  
                  <!-- pagination-wrapper -->
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <!-- CONTAINER END -->
    </div>
  </div>
  <!--app-content close-->

  </div> {% include 'dashboard/layout/footer.html' %} {% endblock %}