dashboard/urls.py
from django.urls import path
from .views import *
app_name='dashboard'

urlpatterns = [
    path('', Dashboard.as_view(), name='dashboard'),
    path('signup/', user_signup, name='signup'),
    path('logout/', user_logout, name='logout'),
    path('login/', user_login, name='user_login'),
    path('profile/', ProfileView.as_view(), name='profile_view'),
    path('courses/', ShortTermCourses.as_view(), name='short_term_courses'),
    path('courses/add/', CourseCreate.as_view(), name='course_create'),
    path('courses/<str:course_id>/edit/', CourseEdit.as_view(), name='course_edit'),
    path('courses/<str:course_id>/delete/', CourseDelete.as_view(), name='course_delete'),
    
]

eduportal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('dashboard.urls')),
    
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

dashboard/models.py
from django.db import models

# Create your models here.
class Course(models.Model):
    title = models.CharField(max_length=250, blank=True)
    subtitle = models.CharField(max_length=250, blank=True)
    amount = models.PositiveIntegerField(null=True, blank=True)
    description = models.TextField(blank=True, null=True)
    image = models.FileField(upload_to='course_images', blank=True, null=True)
    is_active = models.BooleanField("Active",default=True)
    created_at = models.DateTimeField(auto_now_add=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True, blank=True)
    
    def __str__(self):
        return self.title

dashboard/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from dashboard.models import Course

class SignupForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ['username', 'password1', 'password2']

class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)
    
    

class CourseForm(forms.ModelForm):
    name = forms.CharField( 
        label="Title", max_length=100,min_length=2, required = True,
        widget=forms.TextInput(attrs={'autocomplete':'off', 'class': 'pop-input-feild'}),
        error_messages={ 'required': 'The name should not be empty',
                        'min_length': 'The name should not be less than 2 characters',
                        'max_length': 'The name should not exceed 100 characters',
                        }
    )
    
    description = forms.CharField(
        widget=forms.Textarea(attrs={"class": "login-input-feild", "maxlength": 100})
    )
  
    from_age = forms.IntegerField(
         label="From age", required=True,
         widget=forms.TextInput(),
         error_messages={'required': 'The from age should not be empty',
                         'invalid': 'invalid age'}
    )
    to_age = forms.IntegerField(
         label="To age", required=True,
         widget=forms.TextInput(),
         error_messages={'required': 'The to age should not be empty',
                         'invalid': 'invalid age'}
    )
    class Meta:
        model = Course
        fields = ['name', 'description','from_age','to_age']
    
    def clean(self):
        cleaned_data = super(CourseForm, self).clean()
        from_age = cleaned_data.get("from_age")
        to_age = cleaned_data.get("to_age")
        if from_age and to_age and to_age < from_age:
            self.add_error('to_age', 'To age should be greater than from age.')
        return cleaned_data 

dashboard/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout 
from .forms import UserCreationForm, LoginForm
from django.shortcuts import render
from django.views import View
from django.shortcuts import redirect
from django.http import HttpResponseRedirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View
from .models import Course
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.core.paginator import *
from django.shortcuts import get_object_or_404
from django.db import transaction
from .helper import is_ajax
from django.contrib.auth.models import User
from django.contrib import messages



# Create your views here.
def index(request):
    return render(request, 'index.html')


def user_signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = UserCreationForm()
    return render(request, 'signup.html', {'form': form})


def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(request, username=username, password=password)
            if user:
                login(request, user)    
                return HttpResponseRedirect('/')
    else:
        form = LoginForm()
    return render(request, 'dashboard/login.html', {'form': form})


def user_logout(request):
    logout(request)
    return redirect('login')


class Dashboard(LoginRequiredMixin,View):
    template_name = "dashboard/index.html"
    def get(self, request, *args, **kwargs):
        datas = {}
        return render(request, self.template_name, datas)
    

class ProfileView(LoginRequiredMixin,View):
    template_name = "dashboard/profile/index.html"
    def get(self, request, *args, **kwargs):
        datas = {}
        datas['user_id']= request.user.id
        return render(request, self.template_name, datas)
    
    def post(self, request, *args, **kwargs):
        userid = request.POST.get('user_id')
        current_passowrd =  request.POST.get('current_passowrd')
        pwd = request.POST.get('new_password')
        cpwd = request.POST.get('confirm_password')

        try:
            user = User.objects.get(pk=userid)
        except User.DoesNotExist:
            user = None
        if pwd == cpwd:
        
            if user:
                user.set_password(pwd)
                user.save()
                messages.success(request, 'password change success')
                return HttpResponseRedirect('/')
            else:
                messages.error(request, 'Please Try again')
                return render(request, 'dashboard/profile/index.html')

        else:
            messages.error(request, "password doesnot match")
            return render(request, 'dashboard/profile/index.html')

    

class ShortTermCourses(LoginRequiredMixin, View):
    template_name = "dashboard/courses/index.html"
    
    def get(self, request, *args, **kwargs):
        filter_conditions = {}
        
        if is_ajax(request=request):
            query = request.GET.get('query', None)
            filter_conditions['title__icontains'] = query
            
        courses = Course.objects.filter(**filter_conditions)
        try:
            page = int(request.GET.get("page", 1))
        except ValueError:
            page = 1

        paginator = Paginator(courses, 2)

        try:
            courses = paginator.page(page)
        except PageNotAnInteger:
            courses = paginator.page(1)  
        except EmptyPage:
            courses = paginator.page(paginator.num_pages)
            
        if is_ajax(request=request):
            context = {}
            context['courses']= courses
            response = {"status": True,
                        "pagination": render_to_string("dashboard/courses/courses_pagination.html", context=context, request=request),
                        "template": render_to_string("dashboard/courses/courses_list.html", context, request=request),}
            return JsonResponse(response)
            
        datas = {'courses':courses, 'current_page': page}
        return render(request, self.template_name, datas)
    

class CourseCreate(LoginRequiredMixin, View):
    template_name = "dashboard/courses/course_form.html"

    def get(self, request, *args, **kwargs):
        data = {}
        context = {}
        return render(request, self.template_name, context)

    def post(self, request, *args, **kwargs):
        response = {}
       
        try:
            with transaction.atomic():
                create_conditions, data = {}, {}
                title = request.POST.get('title', None)
                subtitle = request.POST.get('subtitle', None)
                description = request.POST.get('description', None)
                amount = request.POST.get('amount', None)
                status = request.POST.get('status', None)
                course_image = request.FILES.get('course_image', None)
                
                # CHECK THE DATA EXISTS
                if Course.objects.filter(title=title).exists():
                    data['status'] = False
                    data['message'] = 'Data already exists'
                else:
                    if title:
                        create_conditions['title']= title
                    if subtitle:
                        create_conditions['subtitle']= subtitle
                    if description:
                        create_conditions['description']= description
                    if amount:
                        create_conditions['amount']= amount
                    if status:
                        create_conditions['is_active']= True
                    if course_image:
                        create_conditions['image']= course_image
                    Course.objects.create(**create_conditions)
                    data['status'] = True
                    data['message'] = 'course created successfully'
                    data['redirect_url'] = '/courses/'
        except Exception as error:
            response["status"] = False
            response["message"] = "Something went wrong"
       
        return JsonResponse(data)
    
    

class CourseEdit(LoginRequiredMixin, View):
    template_name = "dashboard/courses/course_form.html"

    def get(self, request, course_id, *args, **kwargs):
        course = get_object_or_404(Course, id=course_id)
        context = {'course': course, 'id':course_id}
        return render(request, self.template_name, context)

    def post(self, request, course_id, *args, **kwargs):
        response = {}
        try:
            with transaction.atomic():
                update_conditions, data = {}, {}
                
                # Retrieve data from the POST request
                title = request.POST.get('title', None)
                subtitle = request.POST.get('subtitle', None)
                description = request.POST.get('description', None)
                amount = request.POST.get('amount', None)
                status = request.POST.get('status', None)
                course_image = request.FILES.get('course_image', None)
                
                # CHECK THE DATA EXISTS
                if Course.objects.exclude(id=course_id).filter(title=title).exists():
                    data['status'] = False
                    data['message'] = 'Data already exists'
                else:
                    if title:
                        update_conditions['title'] = title
                    if subtitle:
                        update_conditions['subtitle'] = subtitle
                    if description:
                        update_conditions['description'] = description
                    if amount:
                        update_conditions['amount'] = amount
                    if status:
                        update_conditions['is_active'] = True
                    if course_image:
                        update_conditions['image'] = course_image
                    
                    # Update the existing course instance
                    Course.objects.filter(id=course_id).update(**update_conditions)
                    print('pppojoj')
                    
                    data['status'] = True
                    data['message'] = 'Course updated successfully'
                    data['redirect_url'] = '/courses/'
        except Exception as error:
            response["status"] = False
            response["message"] = "Something went"
        return JsonResponse(data)
    
    
    
class CourseDelete(LoginRequiredMixin, View):
    template_name = "dashboard/courses/course_form.html"

    def get(self, request, course_id, *args, **kwargs):
        response = {}
        try:
            with transaction.atomic():
                course = get_object_or_404(Course, id=course_id)
                course.delete()
                return HttpResponseRedirect('/courses/')
        except Exception as error:
            response["status"] = False
            response["message"] = f"Error: {error}"

        return JsonResponse(response)

templates/dashboard/index.html
{% extends "dashboard/layout/base.html" %} 
{% load static %} 
{% block body_block %}

{% include 'dashboard/layout/header.html' %}

<!--app-content open-->
           <div class="main-content app-content mt-0">
               <div class="side-app">

                   <!-- CONTAINER -->
                   <div class="main-container container-fluid">

                       <!-- PAGE-HEADER -->
                       <div class="page-header">
                           <h1 class="page-title">Dashboard</h1>
                           <div>
                               <ol class="breadcrumb">
                                   <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                                   <li class="breadcrumb-item active" aria-current="page">Dashboard</li>
                               </ol>
                           </div>
                       </div>
                       <!-- PAGE-HEADER END -->

                        <!-- ROW OPEN -->
                       <div class="row">
                           <div class="col-sm-6 col-md-6 col-lg-6 col-xl-3">
                               <div class="card bg-primary img-card box-primary-shadow">
                                   <div class="card-body">
                                       <div class="d-flex">
                                           <div class="text-white">
                                               <h2 class="mb-0 number-font">7,865</h2>
                                               <p class="text-white mb-0">Contacts</p>
                                           </div>
                                           <div class="ms-auto"> <i class="fa fa-phone text-white fs-30 me-2 mt-2"></i> </div>
                                       </div>
                                   </div>
                               </div>
                           </div>
                       
                       </div>
                       <!-- ROW CLOSED -->



                   </div>
                   <!-- CONTAINER END -->
               </div>
           </div>
           <!--app-content close-->
           
           {% include 'dashboard/layout/footer.html' %}
{% endblock %}

templates/dashboard/login.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    {% load static %}

    <head>
        <!-- META DATA -->
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />

        <!-- FAVICON -->
        <link rel="shortcut icon" type="image/x-icon" href="assets/images_ex/fav.png" />

        <!-- TITLE -->
        <title>Join IT Tech Admin | Login</title>

        <!-- BOOTSTRAP CSS -->
        <link id="style" href="{% static '/assets/plugins/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet" />

        <!-- STYLE CSS -->
        <link href="{% static '/assets/css/style.css' %}" rel="stylesheet" />
        <link href="{% static '/assets/css/style-custom.css' %}" rel="stylesheet" />
        <link href="{% static '/assets/css/dark-style.css' %}" rel="stylesheet" />
        <link href="{% static '/assets/css/transparent-style.css' %}" rel="stylesheet" />
        <link href="{% static '/assets/css/skin-modes.css' %}" rel="stylesheet" />

        <!--- FONT-ICONS CSS -->
        <link href="{% static '/assets/css/icons.css' %}" rel="stylesheet" />

        <!-- COLOR SKIN CSS -->
        <link id="theme" rel="stylesheet" type="text/css" media="all" href="{% static '/assets/colors/color1.css' %}" />
    </head>

    <body class="app sidebar-mini ltr login-img">
        <!-- BACKGROUND-IMAGE -->
        <div class="">
            <!-- PAGE -->
            <div class="page">
                <div class="">
                    <!-- CONTAINER OPEN -->

                    <div class="container-login100">
                        <div class="wrap-login100 p-6">
                            <div class="col col-login mx-auto m-5">
                                <div class="text-center">
                                    <a href="index.php"><img src="{% static '/assets/images_ex/logo.png' %}" class="header-brand-img" alt="" /></a>
                                </div>
                            </div>

                            <form class="login100-form validate-form signin-form" id="signinForm" action="{% url 'dashboard:user_login' %}" method="post">
                                {% csrf_token %}
                                <div class="wrap-input100 validate-input input-group" data-bs-validate="Valid email is required: ex@abc.xyz">
                                    <a href="javascript:void(0)" class="input-group-text bg-white text-muted">
                                        <i class="zmdi zmdi-email text-white" aria-hidden="true"></i>
                                    </a>
                                    {% comment %} <input class="input100 border-start-0 form-control ms-0" name="email" type="email" placeholder="Email" /> {% endcomment %}
                                    {{form.username}}
                                </div>
                                <div class="wrap-input100 validate-input input-group" id="Password-toggle">
                                    <a href="javascript:void(0)" class="input-group-text bg-white text-muted">
                                        <i class="zmdi zmdi-eye text-white" aria-hidden="true"></i>
                                    </a>
                                    {% comment %} <input class="input100 border-start-0 form-control ms-0" name="password" type="password" placeholder="Password" /> {% endcomment %}
                                    {{form.password}}

                                </div>

                                <div class="container-login100-form-btn">
                                    <button class="login100-form-btn btn-primary signbtn">Sign Up</button> 
                                </div>
                            </form>
                        </div>
                    </div>
                    <!-- CONTAINER CLOSED -->
                </div>
            </div>
            <!-- End PAGE -->
        </div>
        <!-- BACKGROUND-IMAGE CLOSED -->

        <!-- JQUERY JS -->
        <script src="{% static '/assets/js/jquery.min.js' %}"></script>

        <!-- BOOTSTRAP JS -->
        <script src="{% static '/assets/plugins/bootstrap/js/popper.min.js' %}"></script>
        <script src="{% static '/assets/plugins/bootstrap/js/bootstrap.min.js' %}"></script>

        <!-- SHOW PASSWORD JS -->
        <script src="{% static '/assets/js/show-password.min.js' %}"></script>

        <!-- GENERATE OTP JS -->
        <script src="{% static '/assets/js/generate-otp.js' %}"></script>

        <!-- Perfect SCROLLBAR JS-->
        <script src="{% static '/assets/plugins/p-scroll/perfect-scrollbar.js' %}"></script>

        <!-- Color Theme js -->
        <script src="{% static '/assets/js/themeColors.js' %}"></script>

        <!-- CUSTOM JS -->
        <script src="{% static '/assets/js/custom.js' %}"></script>
        {% comment %} <script src="{% static '/dashboard/login.js' %}"></script> {% endcomment %}

    </body>
</html>

templates/dashboard/status_message.html
{% load static %}
<div class="flash_message error" style="display:none;" id="flash_message_error">
	<span class="icon">
	<img src="{% static '/assets/images/pngs/cross.png' %}"/>
    </span>
	<span class="msg msg_desc"></span>
</div>

<div class="flash_message success" style="display: none" id="flash_message_success">
			<span class="icon">
			<img src="{% static '/assets/images/pngs/success.png' %}"/></span>
			<span class="msg msg_desc"></span>
</div>
<div class="flash_message warning" style="display: none" id="flash_message_warning">
			<span class="icon">
			<img src="{% static '/assets/images/pngs/warning.png' %}"/></span>
			<span class="msg msg_desc"></span>
</div>